[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "torchdae"
version = "0.1.0"
description = "GPU-parallel, fully differentiable implicit DAE solvers in PyTorch."
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name = "Yousef Gamaleldin", email = "yrafat38@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Mathematics",
]
dependencies = [
    "torch>=2.0.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["torchdae*"]
